### ISSUE TITLE
AUTH_KEY

### ISSUE THREAD

**Issue by reichigo** [emreyalvac/firebase-rs#14]
Hi guys, how can I find AUTH_KEY in my firebase console?
thanks

**Comment by aadeg** [comment]
Same issue here

**Comment by reichigo** [comment]
i'm trying and i can't connect to firestore but after so long i got it with realtime database.
To connect in realtime go to menu 
![image](https://user-images.githubusercontent.com/1075628/183425950-57123d5a-1385-4a23-99bc-6f7f3625665e.png)

copy the all url 
![image](https://user-images.githubusercontent.com/1075628/183426484-c065682b-ef4b-48a3-af25-1293e0092bfd.png)

To find auth_url go to project settings
![image](https://user-images.githubusercontent.com/1075628/183427287-2e9f4e33-01e2-4a6d-bd7c-602a796f8877.png)

services account 
![image](https://user-images.githubusercontent.com/1075628/183427458-5ae312e8-c5bb-4198-8407-cbeb32222948.png)

database secrets and copy the secret 

![image](https://user-images.githubusercontent.com/1075628/183427762-e5e37c0c-38b1-456a-b333-58753db6b6cc.png)

Its work to connect in the realtime but I still can not the firestore database

**Comment by adminSxs** [comment]
> i'm trying and i can't connect to firestore but after so long i got it with realtime database. To connect in realtime go to menu ![image](https://user-images.githubusercontent.com/1075628/183425950-57123d5a-1385-4a23-99bc-6f7f3625665e.png)
> 
> copy the all url ![image](https://user-images.githubusercontent.com/1075628/183426484-c065682b-ef4b-48a3-af25-1293e0092bfd.png)
> 
> To find auth_url go to project settings ![image](https://user-images.githubusercontent.com/1075628/183427287-2e9f4e33-01e2-4a6d-bd7c-602a796f8877.png)
> 
> services account ![image](https://user-images.githubusercontent.com/1075628/183427458-5ae312e8-c5bb-4198-8407-cbeb32222948.png)
> 
> database secrets and copy the secret
> 
> ![image](https://user-images.githubusercontent.com/1075628/183427762-e5e37c0c-38b1-456a-b333-58753db6b6cc.png)
> 
> Its work to connect in the realtime but I still can not the firestore database

do you resolve this problems?
