### ISSUE TITLE
Basic question about scope of this project

### ISSUE THREAD

**Issue by hut8** [emreyalvac/firebase-rs#15]
Is this project intended only for Firebase's Firestore Database? It seems that way, although I could be mistaken. For users who find this crate while looking for a Rust binding to Firebase Analytics, Realtime Database, Authentication, etc., this is confusing. Could you please clarify? There is no API that resembles that of the C++ bindings for Authentication, for example: https://firebase.google.com/docs/auth/cpp/start?authuser=0&hl=en

**Comment by Skaldebane** [comment]
I think it should be renamed to indicate that it's only for Firestore and/or Realtime Database, since someone looking for a Firebase crate is probably looking for one that implements most (if not all) Firebase API features just like the official ones in other languages.

**Comment by emreyalvac** [comment]
We will support all Firebase infrastructure. ASAP

@Skaldebane
