### ISSUE TITLE
unwrap()

### ISSUE THREAD

**Issue by y2kappa** [emreyalvac/firebase-rs#3]
Hi,

Thanks for working on this. It's really great to have this functionality working out of the box with a lib from `crates.io`. I am integrating it into my server, but I have an issue. I think there are too many unwraps in the `library` and it doesn't seem I can avoid them. 

`get_generic` unwraps and sometimes I don't know if the path exists and I don't want it to unwrap, I just want an error. 

Do you accept PRs to make these as result instead?

Thanks

**Comment by emreyalvac** [comment]
Hi @y2kappa,

Thanks for issue.

You're right but lib. is still under development. If u want to send PR, of course i will accept.

Good works.

**Comment by Bobbbay** [comment]
Even better would be to implement `Error` on the error types. This way, you can `?` out of them. It's astonishing that none of the errors in this crate don't have this done, especially since it's the standard way of create error enums in Rust - and it takes less than a minute to do!
